### ISSUE TITLE
animal / insect query causing server error

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#34]
http://gimmefreshdata.github.io/?taxonSelector=Animalia%2CInsecta&traitSelector=&wktString=ENVELOPE(-150%2C-50%2C40%2C10)

causes unexpected server error

**Comment by jhpoelen** [comment]
Look like this (massive) search is causing an out-of-memory error, preventing the list to be generated. 

```
16/06/10 13:28:12 WARN TaskSetManager: Lost task 73.0 in stage 2.0 (TID 11140, apihack-c18.idigbio.org): java.lang.OutOfMemoryError: GC overhead limit exceeded
    at org.apache.spark.unsafe.types.UTF8String.fromBytes(UTF8String.java:89)
    at org.apache.spark.sql.execution.columnar.STRING$.extract(ColumnType.scala:406)
    at org.apache.spark.sql.execution.columnar.STRING$.extract(ColumnType.scala:390)
    at org.apache.spark.sql.execution.columnar.compression.DictionaryEncoding$Encoder.compress(compressionSchemes.scala:256)
    at org.apache.spark.sql.execution.columnar.compression.CompressibleColumnBuilder$class.build(CompressibleColumnBuilder.scala:107)
    at org.apache.spark.sql.execution.columnar.NativeColumnBuilder.build(ColumnBuilder.scala:97)
    at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1$$anonfun$next$2.apply(InMemoryColumnarTableScan.scala:166)
    at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1$$anonfun$next$2.apply(InMemoryColumnarTableScan.scala:166)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
    at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:166)
    at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$3$$anon$1.next(InMemoryColumnarTableScan.scala:130)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:357)
    at org.apache.spark.serializer.SerializationStream.writeAll(Serializer.scala:153)
    at org.apache.spark.storage.BlockManager.dataSerializeStream(BlockManager.scala:1196)
    at org.apache.spark.storage.DiskStore$$anonfun$putIterator$1.apply$mcV$sp(DiskStore.scala:81)
    at org.apache.spark.storage.DiskStore$$anonfun$putIterator$1.apply(DiskStore.scala:81)
    at org.apache.spark.storage.DiskStore$$anonfun$putIterator$1.apply(DiskStore.scala:81)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1250)
    at org.apache.spark.storage.DiskStore.putIterator(DiskStore.scala:82)
    at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:798)
    at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:645)
    at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:153)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
```

**Comment by jhpoelen** [comment]
After upgrading to spark 1.6.1, the issue was no longer observed. The monitors ended up including ~80M occurrences from southern part of North America and parts of Middle America (see attached screenshot).

![screen shot 2016-06-10 at 2 51 41 pm](https://cloud.githubusercontent.com/assets/1084872/15979778/fedf78ae-2f1a-11e6-85e5-dfc8d139c760.png)
