### ISSUE TITLE
invoking updateAll causes cancelled tasks in spark job 

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#44]
stacktrace:

```
java.lang.RuntimeException: string matching regex `(datetime|string)' expected but `k' found
    at scala.sys.package$.error(package.scala:27)
    at OccurrenceSelectors$.traitSelector(OccurrenceSelectors.scala:25)
    at OccurrenceSelectors$$anonfun$apply$1$$anonfun$apply$2.apply(OccurrenceSelectors.scala:51)
    at OccurrenceSelectors$$anonfun$apply$1$$anonfun$apply$2.apply(OccurrenceSelectors.scala:51)
    at OccurrenceSelectors$$anonfun$apply$1$$anonfun$apply$5.apply(OccurrenceSelectors.scala:52)
    at OccurrenceSelectors$$anonfun$apply$1$$anonfun$apply$5.apply(OccurrenceSelectors.scala:52)
    at scala.collection.LinearSeqOptimized$class.forall(LinearSeqOptimized.scala:70)
    at scala.collection.immutable.List.forall(List.scala:84)
    at OccurrenceSelectors$$anonfun$apply$1.apply(OccurrenceSelectors.scala:52)
    at OccurrenceSelectors$$anonfun$apply$1.apply(OccurrenceSelectors.scala:51)
    at OccurrenceCollectionBuilder$$anonfun$selectOccurrences$4$$anonfun$apply$2.apply(OccurrenceCollectionGenerator.scala:315)
    at OccurrenceCollectionBuilder$$anonfun$selectOccurrences$4$$anonfun$apply$2.apply(OccurrenceCollectionGenerator.scala:314)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
    at OccurrenceCollectionBuilder$$anonfun$selectOccurrences$4.apply(OccurrenceCollectionGenerator.scala:314)
    at OccurrenceCollectionBuilder$$anonfun$selectOccurrences$4.apply(OccurrenceCollectionGenerator.scala:314)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
```

![screen shot 2016-08-17 at 3 22 32 pm](https://cloud.githubusercontent.com/assets/1084872/17755401/ae43e6d8-648e-11e6-994d-34824c741f9a.png)

**Comment by jhpoelen** [comment]
Root cause was malformed monitors that included body size constraints. The monitors have been removed. See #43 for a description of desired enhancement.
