### ISSUE TITLE
unsupported traitselector causes monitor update to stall

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#46]
If monitor with unsupported traitselector is injected, the monitor update stalls.
see: 

```
16/08/22 14:49:06 ERROR Executor: Exception in task 34.1 in stage 1.0 (TID 54)
java.lang.RuntimeException: traitSelector from [OccurrenceSelector(Aves|Mammalia,POLYGON ((-122.78320312499999 37.13404537126446, -122.78320312499999 38.1777509666256, -121.75048828124999 38.1777509666256, -121.75048828124999 37.13404537126446, -122.78320312499999 37.13404537126446)),bodyMass < 50 g,Some(15463102))] failed to parse: [[1.15] failure: string matching regex `(datetime|string)' expected but `g' found

bodyMass < 50 g
              ^.msg]
    at scala.sys.package$.error(package.scala:27)
    at OccurrenceSelectors$.traitSelector(OccurrenceSelectors.scala:25)
```

**Comment by jhpoelen** [comment]
@jhammock this is the reason why the neon triggered monitor still hasn't completed. Looking into better ways to avoid invalid monitors.

**Comment by jhpoelen** [comment]
Fixed by making traitselector parser more lenient. Instead of blowing up, the resulting traitselector never selects any data and the spark job logs a message indicating of the unsupported traitselector.
